//! Build script that bundles `src-gui/dist` into a single zip and writes it to `OUT_DIR`
//! for release builds.
//!
//! The resulting zip is embedded into the plugin binary via `include_bytes!` in `gui.rs`
//! and served at runtime by the WebView under the `wxp-plugin://` scheme.
//! In debug builds Vite's dev server is used instead, so this script does nothing.

use std::collections::HashSet;
use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use wrac_build::{FrontendBundleConfig, build_frontend_bundle};

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest_path = manifest_dir.join("Cargo.toml");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    // Make [package.metadata.wrac] in Cargo.toml the single source of truth for plugin
    // identity. The plugin descriptor table is generated from it below, while xtask reads
    // the same manifest directly for wrapper and artifact names.
    let metadata = read_wrac_metadata(&manifest_path).expect("failed to read WRAC metadata");
    write_plugin_products(&metadata, &out_dir)
        .expect("failed to write WRAC plugin product metadata");

    let gui_dist_dir = manifest_dir
        .parent()
        .expect("src-plugin must have a parent directory")
        .join("src-gui")
        .join("dist");
    build_frontend_bundle(FrontendBundleConfig {
        dist_dir: gui_dist_dir,
        output_file_name: "wrac_gain_plugin_gui.zip",
        rerun_if_changed: &[
            "../src-gui/index.html",
            "../src-gui/src",
            "../src-gui/package.json",
            "../src-gui/vite.config.ts",
        ],
        missing_dist_build_command:
            "Run `npm install && npm run build` in src-gui before release builds.",
    })
    .expect("failed to create frontend zip");
}

fn write_plugin_products(metadata: &WracMetadata, out_dir: &Path) -> io::Result<()> {
    // Rust cannot iterate over Cargo manifest metadata at compile time. Generate the
    // descriptor table once in build.rs so the plugin factory still has a static,
    // allocation-free source for count/descriptor/create queries.
    let mut rust =
        String::from("// Generated by build.rs from package.metadata.wrac. Do not edit by hand.\n");
    rust.push_str(&format!(
        "pub(crate) const COMPANY_NAME: &str = {:?};\n",
        metadata.company_name
    ));
    rust.push_str(&format!(
        "pub(crate) const AUV2_MANUFACTURER_CODE: [u8; 4] = {};\n",
        four_ascii_array_literal(&metadata.auv2_manufacturer_code)
    ));
    rust.push_str(&format!(
        "pub(crate) const AAX_MANUFACTURER_ID: u32 = {};\n",
        fourcc_literal(&metadata.aax_manufacturer_id)
    ));
    rust.push_str(&format!(
        "pub(crate) const AAX_PACKAGE_VERSION: u32 = {};\n",
        aax_package_version_literal()?
    ));
    // CLAP hosts read feature strings during discovery. Generate them from the
    // manifest so the production-readiness checks and runtime descriptor cannot
    // drift after a product rename or capability change.
    for (index, plugin) in metadata.plugins.iter().enumerate() {
        rust.push_str(&format!(
            "const PLUGIN_{index}_FEATURES: &[PluginFeature] = &{};\n",
            plugin_feature_array_literal(&plugin.clap_features)?
        ));
        // AAX asks for stem configs through C callbacks during package description,
        // before any Rust plugin instance exists. Generate static tables so the
        // callback can be lifetime-independent and allocation-free.
        write_aax_stem_config_statics(&mut rust, index, plugin)?;
        rust.push_str(&format!(
            "unsafe extern \"C\" fn plugin_{index}_aax_get_num_stem_configs() -> u32 {{\n"
        ));
        rust.push_str(&format!(
            "    PLUGIN_{index}_AAX_STEM_CONFIGS.len() as u32\n"
        ));
        rust.push_str("}\n");
        rust.push_str(&format!(
            "unsafe extern \"C\" fn plugin_{index}_aax_get_stem_config(index: u32) -> *const AaxStemConfig {{\n"
        ));
        rust.push_str(&format!(
            "    PLUGIN_{index}_AAX_STEM_CONFIGS.get(index as usize).map_or(core::ptr::null(), |config| config)\n"
        ));
        rust.push_str("}\n");
    }
    rust.push_str("pub(crate) const PLUGIN_DESCRIPTORS: &[PluginDescriptor] = &[\n");
    for (index, plugin) in metadata.plugins.iter().enumerate() {
        rust.push_str("    PluginDescriptor {\n");
        rust.push_str(&format!("        id: {:?},\n", plugin.plugin_id));
        rust.push_str(&format!("        name: {:?},\n", plugin.plugin_name));
        rust.push_str("        vendor: COMPANY_NAME,\n");
        rust.push_str(&format!("        url: {:?},\n", metadata.homepage_url));
        rust.push_str(&format!("        manual_url: {:?},\n", metadata.manual_url));
        rust.push_str(&format!(
            "        support_url: {:?},\n",
            metadata.support_url
        ));
        rust.push_str("        version: env!(\"CARGO_PKG_VERSION\"),\n");
        rust.push_str(&format!(
            "        description: {:?},\n",
            metadata.description
        ));
        rust.push_str(&format!("        features: PLUGIN_{index}_FEATURES,\n"));
        rust.push_str("        auv2: Some(Auv2Descriptor {\n");
        rust.push_str("            manufacturer_code: AUV2_MANUFACTURER_CODE,\n");
        rust.push_str("            manufacturer_name: COMPANY_NAME,\n");
        rust.push_str(&format!(
            "            plugin_type: {},\n",
            four_ascii_array_literal(&plugin.auv2_type)
        ));
        rust.push_str(&format!(
            "            plugin_subtype: {},\n",
            four_ascii_array_literal(&plugin.auv2_subtype)
        ));
        rust.push_str("        }),\n");
        rust.push_str("        vst3: Some(Vst3Descriptor {\n");
        rust.push_str(&format!(
            "            subcategories: {:?},\n",
            plugin.vst3_subcategories
        ));
        rust.push_str(&format!(
            "            component_id: {},\n",
            uuid_array_literal(&plugin.vst3_component_id)?
        ));
        rust.push_str("        }),\n");
        rust.push_str("        aax: Some(AaxDescriptor {\n");
        rust.push_str(&format!(
            "            package_name: {:?},\n",
            metadata.bundle_name
        ));
        rust.push_str("            package_version: AAX_PACKAGE_VERSION,\n");
        rust.push_str(&format!(
            "            categories: {},\n",
            aax_categories_literal(&plugin.aax_categories)?
        ));
        rust.push_str("            manufacturer_id: AAX_MANUFACTURER_ID,\n");
        rust.push_str(&format!(
            "            product_id: {},\n",
            fourcc_literal(&plugin.aax_product_id)
        ));
        rust.push_str(&format!(
            "            get_num_stem_configs: plugin_{index}_aax_get_num_stem_configs,\n"
        ));
        rust.push_str(&format!(
            "            get_stem_config: plugin_{index}_aax_get_stem_config,\n"
        ));
        rust.push_str("        }),\n");
        rust.push_str("    },\n");
    }
    rust.push_str("];\n");
    fs::write(out_dir.join("wrac_plugin_products.rs"), rust)
}

fn four_ascii_array_literal(value: &str) -> String {
    let bytes = value.as_bytes();
    format!("[{}, {}, {}, {}]", bytes[0], bytes[1], bytes[2], bytes[3])
}

fn plugin_feature_array_literal(features: &[String]) -> io::Result<String> {
    let mut items = Vec::new();
    for feature in features {
        items.push(plugin_feature_literal(feature)?);
    }
    Ok(format!("[{}]", items.join(", ")))
}

fn plugin_feature_literal(feature: &str) -> io::Result<&'static str> {
    match feature {
        "audio-effect" => Ok("PluginFeature::AudioEffect"),
        "analyzer" => Ok("PluginFeature::Analyzer"),
        "ambisonic" => Ok("PluginFeature::Ambisonic"),
        "chorus" => Ok("PluginFeature::Chorus"),
        "compressor" => Ok("PluginFeature::Compressor"),
        "de-esser" => Ok("PluginFeature::DeEsser"),
        "delay" => Ok("PluginFeature::Delay"),
        "instrument" => Ok("PluginFeature::Instrument"),
        "note-effect" => Ok("PluginFeature::NoteEffect"),
        "note-detector" => Ok("PluginFeature::NoteDetector"),
        "drum" => Ok("PluginFeature::Drum"),
        "drum-machine" => Ok("PluginFeature::DrumMachine"),
        "equalizer" => Ok("PluginFeature::Equalizer"),
        "expander" => Ok("PluginFeature::Expander"),
        "filter" => Ok("PluginFeature::Filter"),
        "flanger" => Ok("PluginFeature::Flanger"),
        "frequency-shifter" => Ok("PluginFeature::FrequencyShifter"),
        "gate" => Ok("PluginFeature::Gate"),
        "glitch" => Ok("PluginFeature::Glitch"),
        "granular" => Ok("PluginFeature::Granular"),
        "distortion" => Ok("PluginFeature::Distortion"),
        "limiter" => Ok("PluginFeature::Limiter"),
        "mastering" => Ok("PluginFeature::Mastering"),
        "mixing" => Ok("PluginFeature::Mixing"),
        "mono" => Ok("PluginFeature::Mono"),
        "multi-effects" => Ok("PluginFeature::MultiEffects"),
        "phaser" => Ok("PluginFeature::Phaser"),
        "phase-vocoder" => Ok("PluginFeature::PhaseVocoder"),
        "pitch-correction" => Ok("PluginFeature::PitchCorrection"),
        "pitch-shifter" => Ok("PluginFeature::PitchShifter"),
        "restoration" => Ok("PluginFeature::Restoration"),
        "reverb" => Ok("PluginFeature::Reverb"),
        "sampler" => Ok("PluginFeature::Sampler"),
        "stereo" => Ok("PluginFeature::Stereo"),
        "surround" => Ok("PluginFeature::Surround"),
        "synthesizer" => Ok("PluginFeature::Synthesizer"),
        "transient-shaper" => Ok("PluginFeature::TransientShaper"),
        "tremolo" => Ok("PluginFeature::Tremolo"),
        "utility" => Ok("PluginFeature::Utility"),
        _ => Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("unsupported package.metadata.wrac.plugins.clap_features value: {feature}"),
        )),
    }
}

#[derive(Debug, Deserialize)]
struct CargoManifest {
    package: CargoPackage,
}

#[derive(Debug, Deserialize)]
struct CargoPackage {
    metadata: Option<PackageMetadata>,
}

#[derive(Debug, Deserialize)]
struct PackageMetadata {
    wrac: Option<WracMetadata>,
}

#[derive(Debug, Deserialize)]
struct WracMetadata {
    company_name: String,
    auv2_manufacturer_code: String,
    aax_manufacturer_id: String,
    bundle_name: String,
    bundle_identifier: String,
    homepage_url: String,
    manual_url: String,
    support_url: String,
    description: String,
    copyright: String,
    plugins: Vec<WracPluginMetadata>,
}

#[derive(Debug, Deserialize)]
struct WracPluginMetadata {
    plugin_id: String,
    plugin_name: String,
    clap_features: Vec<String>,
    vst3_subcategories: String,
    vst3_component_id: String,
    standalone_name: String,
    auv2_type: String,
    auv2_subtype: String,
    aax_categories: Vec<String>,
    aax_product_id: String,
    aax_stem_configs: Vec<AaxStemConfigMetadata>,
}

#[derive(Debug, Deserialize)]
struct AaxStemConfigMetadata {
    name: String,
    input: String,
    output: String,
    plugin_id: String,
}

fn read_wrac_metadata(manifest_path: &Path) -> io::Result<WracMetadata> {
    let manifest = fs::read_to_string(manifest_path)?;
    let cargo_manifest: CargoManifest = toml::from_str(&manifest)
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?;
    let metadata = cargo_manifest
        .package
        .metadata
        .ok_or_else(missing_wrac_metadata)?
        .wrac
        .ok_or_else(missing_wrac_metadata)?;
    validate_required("package.metadata.wrac.company_name", &metadata.company_name)?;
    validate_four_ascii("auv2_manufacturer_code", &metadata.auv2_manufacturer_code)?;
    validate_four_ascii("aax_manufacturer_id", &metadata.aax_manufacturer_id)?;
    validate_required(
        "package.metadata.wrac.bundle_identifier",
        &metadata.bundle_identifier,
    )?;
    validate_required("package.metadata.wrac.homepage_url", &metadata.homepage_url)?;
    validate_required("package.metadata.wrac.manual_url", &metadata.manual_url)?;
    validate_required("package.metadata.wrac.support_url", &metadata.support_url)?;
    validate_required("package.metadata.wrac.description", &metadata.description)?;
    validate_required("package.metadata.wrac.copyright", &metadata.copyright)?;
    if metadata.plugins.is_empty() {
        return Err(missing_metadata("plugins"));
    }
    let mut plugin_ids = HashSet::new();
    let mut standalone_names = HashSet::new();
    let mut auv2_ids = HashSet::new();
    for plugin in &metadata.plugins {
        validate_required("package.metadata.wrac.plugins.plugin_id", &plugin.plugin_id)?;
        validate_required(
            "package.metadata.wrac.plugins.plugin_name",
            &plugin.plugin_name,
        )?;
        validate_non_empty_list(
            "package.metadata.wrac.plugins.clap_features",
            &plugin.clap_features,
        )?;
        for feature in &plugin.clap_features {
            plugin_feature_literal(feature)?;
        }
        validate_required(
            "package.metadata.wrac.plugins.vst3_subcategories",
            &plugin.vst3_subcategories,
        )?;
        uuid_array_literal(&plugin.vst3_component_id)?;
        validate_required(
            "package.metadata.wrac.plugins.standalone_name",
            &plugin.standalone_name,
        )?;
        validate_four_ascii("auv2_type", &plugin.auv2_type)?;
        validate_four_ascii("auv2_subtype", &plugin.auv2_subtype)?;
        validate_non_empty_list(
            "package.metadata.wrac.plugins.aax_categories",
            &plugin.aax_categories,
        )?;
        for category in &plugin.aax_categories {
            aax_category_literal(category)?;
        }
        validate_four_ascii("plugins.aax_product_id", &plugin.aax_product_id)?;
        if plugin.aax_stem_configs.is_empty() {
            return Err(missing_metadata("plugins.aax_stem_configs"));
        }
        let mut aax_plugin_ids = HashSet::new();
        for stem_config in &plugin.aax_stem_configs {
            validate_required(
                "package.metadata.wrac.plugins.aax_stem_configs.name",
                &stem_config.name,
            )?;
            aax_stem_format_literal(&stem_config.input)?;
            aax_stem_format_literal(&stem_config.output)?;
            validate_four_ascii("plugins.aax_stem_configs.plugin_id", &stem_config.plugin_id)?;
            validate_unique(
                "aax_stem_configs.plugin_id",
                &stem_config.plugin_id,
                &mut aax_plugin_ids,
            )?;
        }
        validate_unique("plugin_id", &plugin.plugin_id, &mut plugin_ids)?;
        validate_unique(
            "standalone_name",
            &plugin.standalone_name,
            &mut standalone_names,
        )?;
        if !auv2_ids.insert((plugin.auv2_type.as_str(), plugin.auv2_subtype.as_str())) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "package.metadata.wrac.plugins AUv2 type/subtype must be unique: {}/{}",
                    plugin.auv2_type, plugin.auv2_subtype
                ),
            ));
        }
    }
    Ok(metadata)
}

fn validate_non_empty_list(key: &str, values: &[String]) -> io::Result<()> {
    if values.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{key} must not be empty"),
        ));
    }
    for value in values {
        validate_required(key, value)?;
    }
    Ok(())
}

fn missing_metadata(key: &str) -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        format!("missing package.metadata.wrac.{key} in src-plugin/Cargo.toml"),
    )
}

fn missing_wrac_metadata() -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        "missing package.metadata.wrac in src-plugin/Cargo.toml",
    )
}

fn validate_required(key: &str, value: &str) -> io::Result<()> {
    if value.is_empty() {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{key} must not be empty"),
        ))
    } else {
        Ok(())
    }
}

fn validate_four_ascii(key: &str, value: &str) -> io::Result<()> {
    if value.len() == 4 && value.is_ascii() {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("package.metadata.wrac.{key} must be exactly 4 ASCII bytes"),
        ))
    }
}

fn fourcc_literal(value: &str) -> String {
    let bytes = value.as_bytes();
    format!(
        "0x{:02X}{:02X}{:02X}{:02X}",
        bytes[0], bytes[1], bytes[2], bytes[3]
    )
}

fn aax_categories_literal(categories: &[String]) -> io::Result<String> {
    let mut values = Vec::new();
    for category in categories {
        values.push(aax_category_literal(category)?);
    }
    Ok(values.join(" | "))
}

fn aax_category_literal(category: &str) -> io::Result<&'static str> {
    // Keep the manifest vocabulary human-readable, but emit the AAX bit values
    // directly so the runtime crate does not need to link against Avid headers.
    match category {
        "eq" => Ok("0x0000_0001"),
        "dynamics" => Ok("0x0000_0002"),
        "pitch-shift" => Ok("0x0000_0004"),
        "reverb" => Ok("0x0000_0008"),
        "delay" => Ok("0x0000_0010"),
        "modulation" => Ok("0x0000_0020"),
        "harmonic" => Ok("0x0000_0040"),
        "noise-reduction" => Ok("0x0000_0080"),
        "dither" => Ok("0x0000_0100"),
        "sound-field" => Ok("0x0000_0200"),
        "hardware-generator" => Ok("0x0000_0400"),
        "software-generator" => Ok("0x0000_0800"),
        "wrapped-plugin" => Ok("0x0000_1000"),
        "effect" => Ok("0x0000_2000"),
        "midi-effect" => Ok("0x0001_0000"),
        _ => Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("unsupported package.metadata.wrac.plugins.aax_categories value: {category}"),
        )),
    }
}

fn write_aax_stem_config_statics(
    rust: &mut String,
    plugin_index: usize,
    plugin: &WracPluginMetadata,
) -> io::Result<()> {
    let mut items = Vec::new();
    for (stem_index, stem_config) in plugin.aax_stem_configs.iter().enumerate() {
        rust.push_str(&format!(
            "static PLUGIN_{plugin_index}_AAX_STEM_{stem_index}_NAME: &[u8] = &{:?};\n",
            nul_terminated(&stem_config.name)
        ));
        items.push(format!(
            "AaxStemConfig {{ name: PLUGIN_{plugin_index}_AAX_STEM_{stem_index}_NAME.as_ptr().cast(), format_in: {}, format_out: {}, plugin_id: {} }}",
            aax_stem_format_literal(&stem_config.input)?,
            aax_stem_format_literal(&stem_config.output)?,
            fourcc_literal(&stem_config.plugin_id)
        ));
    }
    rust.push_str(&format!(
        "static PLUGIN_{plugin_index}_AAX_STEM_CONFIGS: &[AaxStemConfig] = &[{}];\n",
        items.join(", ")
    ));
    Ok(())
}

fn aax_stem_format_literal(format: &str) -> io::Result<&'static str> {
    // The starter template only emits mono/stereo native processing layouts. Add
    // more AAX stem constants here only after the Rust audio-port configuration and
    // validator coverage for those layouts are added together.
    match format {
        "mono" => Ok("1"),
        "stereo" => Ok("0x0001_0002"),
        _ => Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "package.metadata.wrac.plugins.aax_stem_configs format must be mono or stereo: {format}"
            ),
        )),
    }
}

fn nul_terminated(value: &str) -> Vec<u8> {
    // Stem names cross the C ABI as raw pointers; store the terminator in the
    // generated static bytes rather than appending it at callback time.
    let mut bytes = value.as_bytes().to_vec();
    bytes.push(0);
    bytes
}

fn aax_package_version_literal() -> io::Result<String> {
    // AAX package versions are not semantic-version strings. Encoding Cargo's
    // MAJOR.MINOR.PATCH as 0xMMmmpp00 keeps package identity deterministic while
    // leaving the lowest byte unused.
    let major = aax_version_component("CARGO_PKG_VERSION_MAJOR")?;
    let minor = aax_version_component("CARGO_PKG_VERSION_MINOR")?;
    let patch = aax_version_component("CARGO_PKG_VERSION_PATCH")?;
    Ok(format!("0x{major:02X}{minor:02X}{patch:02X}00"))
}

fn aax_version_component(name: &str) -> io::Result<u32> {
    let value = env::var(name)
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?
        .parse::<u32>()
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?;
    if value > 0xFF {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{name} must fit in one byte for AAX package_version: {value}"),
        ));
    }
    Ok(value)
}

fn uuid_array_literal(value: &str) -> io::Result<String> {
    let hex = value.replace('-', "");
    if hex.len() != 32 || !hex.as_bytes().iter().all(u8::is_ascii_hexdigit) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("package.metadata.wrac.plugins.vst3_component_id must be a UUID: {value}"),
        ));
    }
    let mut bytes = [0_u8; 16];
    for (index, byte) in bytes.iter_mut().enumerate() {
        let start = index * 2;
        *byte = u8::from_str_radix(&hex[start..start + 2], 16).map_err(|error| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("package.metadata.wrac.plugins.vst3_component_id must be a UUID: {error}"),
            )
        })?;
    }
    // clap-wrapper applies Steinberg's COM-compatible TUID byte flip before exposing
    // the VST3 class ID. Store the inverse form here so the host-visible CID matches
    // the UUID written in package.metadata.wrac.plugins.vst3_component_id.
    bytes.swap(0, 3);
    bytes.swap(1, 2);
    bytes.swap(4, 5);
    bytes.swap(6, 7);
    Ok(format!("{bytes:?}"))
}

fn validate_unique<'a>(key: &str, value: &'a str, seen: &mut HashSet<&'a str>) -> io::Result<()> {
    if seen.insert(value) {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("package.metadata.wrac.plugins.{key} must be unique: {value}"),
        ))
    }
}
