// Compacts a CLI --viz-dump JSONL trace into src/demoTrace.ts for the GUI's
// browser demo mode. Grid arrays are delta-encoded (null = unchanged).
import { readFileSync, writeFileSync } from "node:fs";

const [, , inPath, outPath] = process.argv;
const lines = readFileSync(inPath, "utf8").trim().split("\n");
const rows = [];
let prevGrid = "";
for (const line of lines) {
  const f = JSON.parse(line);
  const gridKey = JSON.stringify(f.grid);
  const grid = gridKey === prevGrid ? null : f.grid;
  prevGrid = gridKey;
  const tracks = f.tracks.map((tr) => [
    tr.id,
    Math.round(tr.f0 * 10) / 10,
    Math.round(tr.tgt * 10) / 10,
    Math.round(tr.amp * 10) / 10,
    tr.nh,
    tr.nb ? 1 : 0,
  ]);
  rows.push([
    Math.round(f.time * 1000) / 1000,
    Math.round(Math.min(f.flux, 12) * 100) / 100,
    Math.round(f.transient * 100) / 100,
    Math.round(f.in * 10) / 10,
    Math.round(f.res * 10) / 10,
    grid,
    tracks,
  ]);
}

const body = rows.map((r) => JSON.stringify(r)).join(",\n");
const ts = `// Generated by tools: a real engine analysis trace of the phylovox test
// clip (CLI --viz-dump), delta-encoded. Used as the demo feed when the GUI
// runs outside the plugin (plain browser). Do not edit by hand.
import type { VizFrame, VizTrack } from "./types";

type Row = [number, number, number, number, number, number[] | null, number[][]];

const ROWS: Row[] = [
${body},
];

export function demoFrames(): VizFrame[] {
  const frames: VizFrame[] = [];
  let grid: number[] = [];
  ROWS.forEach((row, i) => {
    const [time, flux, transient, inE, res, g, tr] = row;
    if (g !== null) grid = g;
    const tracks: VizTrack[] = tr.map((a) => ({
      id: a[0], f0: a[1], tgt: a[2], amp: a[3], nh: a[4], nb: a[5] === 1,
    }));
    frames.push({
      t: i, time, flux, transient, in: inE, res,
      repeat: true, grid, tracks,
    });
  });
  return frames;
}
`;
writeFileSync(outPath, ts);
console.log(`wrote ${outPath}: ${rows.length} frames, ${(ts.length / 1024).toFixed(0)} KB`);
